github:
  - ".github/**/*"

config:
  - "*"

tests:
  - "src/tests/**/*"

app:
  - "src/app/**/*"

lib:
  - "src/lib/**/*"

headers:
  - "src/inc/**/*"

cmake:
  - "cmake/**/*"
  - "CMakeLists.txt"
  - "CMakePresets.json"
  - "**/CMakeLists.txt"

clang-tidy:
  - ".clang-format"
  - ".clang-tidy"

doc:
  - "doc/**/*"
  - "README.md"
