version: 1
labels:
  # pr title based labels
  - label: 'release'
    title: '^release/.*'

  - label: 'feature'
    title: '^feature/.*'

  - label: 'major'
    title: '^major/.*'

  - label: 'minor'
    title: '^minor/.*'

  - label: 'patch'
    title: '^patch/.*'

  - label: 'chore'
    title: '^chore/.*'

  # pr body based labels
  - label: 'closes-issue'
    body: '(?P<keyword>close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved) ((?P<owner>\w+)\/(?P<repo>\w+))?#(?P<issue>\d+)(\s|$)'
    # ^ based on the linked issues and pull requests documentation from github.
    # ref doc https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
    # ref regex https://regex101.com/r/Cxqyiy/1 by @dacabdi
    # WARNING .editorconfig makes an exception to the line length rule to avoid breaking this regex
    # TODO use multiline and remove exception from .editorconfig

  # pr status based labels
  - label: 'mergeable'
    mergeable: true

  - label: 'work-in-progress'
    mergeable: false

  # pr size based labels
  - label: 'small'
    size-below: 10

  - label: 'medium'
    size-above: 9
    size-below: 100

  - label: 'large'
    size-above: 100
