# ref: https://prettier.io/docs/en/options.html
# the following settings are read from
# .editorconfig to have a single source
# of truth whenever possible
#   - end_of_line
#   - indent_style
#   - indent_size/tab_width
#   - max_line_length
# ref:  https://prettier.io/docs/en/configuration.html#editorconfig
# editorconfig = true
useTabs = false
bracketSameLine = true
bracketSpacing = true
trailingComma = "es5"
singleAttributePerLine = true
proseWrap = "always"
arrowParens = "always"
singleQuote = true
quoteProps = "consistent"
semi = true
